title: Popups
modelClass: Diveramkt\Floatingbanner\Models\Popup
list: $/diveramkt/floatingbanner/models/popup/columns.yaml
recordUrl: 'diveramkt/floatingbanner/popups/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
