list: $/diveramkt/floatingbanner/models/exitpopup/columns.yaml
modelClass: Diveramkt\Floatingbanner\Models\ExitPopup
title: ExitPopups
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/floatingbanner/exitpopups/update/:id'
